DJANGO/brawlstars_project/brawlstars_app/urls.py
from django.urls import path
from .views import search_brawler

app_name = 'brawlstars_app'

urlpatterns = [
    path('search/', search_brawler, name='search_brawler'),
]

DJANGO/brawlstars_project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('brawlstars/', include('brawlstars_app.urls')),
]

DJANGO/brawlstars_project/brawlstars_app/views.py
from django.shortcuts import render
from .utils import fetch_brawler_data

def search_brawler(request):
    if request.method == 'POST':
        brawler_name = request.POST.get('brawler_name')
        brawler_info = fetch_brawler_data(brawler_name)
        return render(request, 'brawler_info.html', {'brawler_info': brawler_info})
    return render(request, 'search_brawler.html')

DJANGO/brawlstars_project/templates/search_brawler.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Search Brawler</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Brawl Stars</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'brawlstars_app:search_brawler' %}">Resultado</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Buscador</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <h1>Search for a Brawler</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="brawler_name" placeholder="Enter brawler name">
        <button type="submit">Search</button>
    </form>
</body>
</html>